// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGbSIcmtSIrUcaWowTTDucMrKb2XggtBw',
    appId: '1:847770296065:web:8e64471e343e827c804500',
    messagingSenderId: '847770296065',
    projectId: 'pmsn20253',
    authDomain: 'pmsn20253.firebaseapp.com',
    storageBucket: 'pmsn20253.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dlkNNtPICIyYBLny-Cj4gvzuSuoAQIs',
    appId: '1:847770296065:android:22143a7ee20262dc804500',
    messagingSenderId: '847770296065',
    projectId: 'pmsn20253',
    storageBucket: 'pmsn20253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSEfTJtlRhi_Ir02jQTGyosjPXQCo4Xs',
    appId: '1:847770296065:ios:833243fb5bdcab2c804500',
    messagingSenderId: '847770296065',
    projectId: 'pmsn20253',
    storageBucket: 'pmsn20253.firebasestorage.app',
    iosBundleId: 'com.example.pmsn20252',
  );
}
